name: Telegram Bot Activation

on:
  schedule:
  - cron: '*/10 * * * *'  # This sets the action to run every 10 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        REMOVEBGKEY: ${{ secrets.REMOVEBGKEY }}
        USER_INFO: ${{ secrets.USER_INFO }}
        MY_TELEGRAM: ${{ secrets.MY_TELEGRAM }}
        OTHER_TELEGRAM: ${{ secrets.OTHER_TELEGRAM }}
      run: python telegram_stickers.py
